export const productzh = [
    {id: "1",image:"./image 29.png",name: "Áo Nam Tay Ngắn",price: "199.000",description: "Áo nam tay ngắn hàng cotton chất lượng cao và giá thành cực tốt."},
    {id: "2",image:"./image 27.png" ,name: "Áo Len Lông Cừu Úc",price: "499.000",description: "Áo len lông cừu Úc sang trọng, giữ ấm cực tốt vào mùa đông."},
    {id: "3",image:"./image 28.png" ,name: "Áo Len Nam Gile",price: "399.000",description: "Áo len lông cừu Úc sang trọng, giữ ấm cực tốt vào mùa đông."},
    {id: "4" ,image:"./image 26.png" ,name: "Áo Len Nam",price: "299.000",description: "Áo len lông cừu Úc sang trọng, giữ ấm cực tốt vào mùa đông."},
    {id: "5",image:"./image 22.png" ,name: "Áo Tay Dài Nữ ",price: "299.000",description: "Áo tay dài nữ thiết kế đơn giản, phù hợp với mọi hoàn cảnh."},
    {id: "6",image:"./image 24.png" ,name: "Áo Len Cổ Tím",price: "399.000",description: "Áo tay dài nữ thiết kế đơn giản, phù hợp với mọi hoàn cảnh." },
    {id: "7",image:"./image 23.png" ,name: "Áo Len Tay Lửng Nữ",price: "299.000",description: "Áo tay dài nữ thiết kế đơn giản, phù hợp với mọi hoàn cảnh."},
    {id: "8",image:"./image 25.png" ,name: "Áo Len Nữ",price: "399.000",description: "Áo tay dài nữ thiết kế đơn giản, phù hợp với mọi hoàn cảnh."},
    {id: "9",image:"./image 33.png",name: "Áo Nam Tay Dài", price: "199.000",description: "Áo nam tay dài thời trang, phong cách trẻ trung và năng động."},
    {id: "10",image:"./image 32.png",name: "Áo Nữ Tay Ngắn", price: "199.000",description: "Áo nữ tay ngắn, phù hợp cho những ngày nắng nóng." },
    {id: "11",image:"./image 31.png", name: "Áo Nam Tay Ngắn", price: "199.000",description: "Áo nam tay ngắn thiết kế đơn giản, phù hợp với các hoàn cảnh khác nhau."},
    {id: "12",image:"./image 30.png",name: "Áo Len Nữ Tay Dài ", price: "199.000",description: "Áo nam tay ngắn thiết kế đơn giản, phù hợp với các hoàn cảnh khác nhau."},
    {id: "13",image:"./013.png" ,name: "Bộ Áo Thun Nam ",price: "699.000",description: " Bộ đồ áo thun nam thời trang và dễ phối đồ, phù hợp cho các hoạt động ngoài trời và hàng ngày."},
    {id: "14",image:"./014.png" ,name: "Bộ Đồ Mặc Nhà Siêu Mát",price: "199.000",description: "Bộ đồ mặc nhà nam với chất liệu mát mẻ, mang đến sự thoải mái và dễ chịu trong mọi hoàn cảnh."},
    {id: "15",image:"./015.png" ,name: "Bộ Quần Hoạ Tiết",price: "599.000",description: " Bộ quần nam hoạ tiết sành điệu, phong cách và thu hút ánh nhìn."},
    {id: "16",image:"./016.png" ,name: "Bộ Mặc Nhà Phong Cách",price: "399.000",description: "Bộ đồ mặc nhà nam phong cách với thiết kế hiện đại và đường nét tinh tế, thích hợp cho những ai yêu thích sự sang trọng và thoải mái."},
    {id: "17",image:"./009.png" ,name: "Bộ Mặc Nhà Nữ ",price: "299.000", description: "Bộ đồ mặc nhà nữ thoải mái, phong cách dễ chịu cho giấc ngủ ngon."},
    {id: "18",image:"./010.png" ,name: "Bộ Đồ Mặc Nhà",price: "399.000", description: "Bộ đồ mặc nhà với thiết kế đơn giản và chất liệu thoáng mát, phù hợp cho các hoạt động nghỉ ngơi trong nhà."},
    {id: "19",image:"./011.png" ,name: "Bộ Mặc Nhà Hoạ Tiết",price: "299.000", description: "Bộ đồ mặc nhà nữ với hoạ tiết nổi bật, mang lại cảm giác trẻ trung và thời thượng."},
    {id: "20",image:"./012.png" ,name: "Bộ Mặc Nhà Phong Cách",price: "399.000", description: " Bộ đồ mặc nhà phong cách với thiết kế hiện đại và đường nét tinh tế, thích hợp cho những ai yêu thích sự sang trọng và thoải mái."},
    {id: "21",image:"./027.png",name: "Áo Len Bé Trai Cổ 3 Phân",price: "499.000",description: " Áo len bé trai có cổ 3 phân thiết kế độc đáo và sang trọng, phù hợp cho các bé trong mùa đông."},
    {id: "22",image:"./028.png" ,name: "Áo Len Bé Trai",price: "299.000",description: " Áo len bé trai đơn giản nhưng không kém phần đáng yêu, là lựa chọn hoàn hảo cho mọi dịp."},
    {id: "23",image:"./029.png" ,name: "Áo Len Bé Trai Đẹp",price: "399.000",description: " Áo len bé trai với thiết kế đẹp mắt, chất liệu mềm mại và giá cả phải chăng."},
    {id: "24",image:"./030.png" ,name: "Áo Len Bé Trai GiLe  ",price: "299.000", description: " Áo len bé trai kiểu gile, mang lại sự thoải mái và ấm áp cho bé trong những ngày se lạnh."},
    {id: "25",image:"./031.png" ,name: "Bộ Shorts Kate Bé Trai ",price: "699.000",description: "Bộ shorts Kate bé trai với thiết kế hiện đại, phong cách trẻ trung và năng động."},
    {id: "26",image:"./032.png" ,name: "Bộ TOLE Lửng Bé Trai",price: "199.000",description: " Bộ thời trang TOLE lửng bé trai, mang đến sự thoải mái và tự do cho bé trong mọi hoạt động."},
    {id: "27",image:"./033.png" ,name: "Bộ Thun Lửng Bé Gái",price: "599.000",description: "Bộ thun lửng bé gái với chất liệu mềm mại và thiết kế đáng yêu, là sự lựa chọn hoàn hảo cho bé gái."},
    {id: "28",image:"./035.png" ,name: "Bộ Shorts Karty Bé Trai",price: "399.000",description: "Bộ shorts Karty bé trai với kiểu dáng thời trang và đường nét tinh tế, phù hợp cho bé trong mọi dịp."},
    {id: "29",image:"./017.png",name: "Áo Len Bé Gái",price: "499.000", description: "Áo len cho bé gái với thiết kế đơn giản nhưng thanh lịch, phù hợp để bé mặc vào mùa đông. Giá cả hợp lý và chất liệu êm ái."},
    {id: "30",image:"./018.png" ,name: "Áo Balo Bé Gái Siêu Mát",price: "299.000", description: "Áo Balo Bé Gái Siêu Mát là sản phẩm thời trang cho bé gái, với chất liệu vải siêu mát và thiết kế thoải mái, phù hợp cho mọi hoạt động hàng ngày."},
    {id: "31",image:"./019.png" ,name: "Áo Len Bé Gái Đẹp",price: "399.000", description: "Áo len bé gái với hoa văn đẹp mắt, tạo điểm nhấn cho trang phục. Phù hợp cho bé mặc đi chơi hoặc đi học."},
    {id: "32",image:"./020.png" ,name: "Áo Len Bé Gái In",price: "299.000", description: "Áo len bé gái in hình với các họa tiết dễ thương, mang lại sự nổi bật và cá tính cho bé."},
    {id: "33",image:"./021.png" ,name: "Bộ Shorts Bé Gái ",price: "699.000" ,description: "Bộ shorts cho bé gái với chất liệu nhẹ và thoáng mát, phù hợp cho các hoạt động ngoài trời. Thiết kế thời trang và dễ phối đồ."},
    {id: "34",image:"./022.png" ,name: "Bộ TOLE Lửng Bé Gái",price: "199.000", description: "Bộ TOLE lửng cho bé gái với màu sắc tươi sáng và thiết kế năng động. Chất liệu vải mềm mại, thoải mái cho bé trong mùa hè."},
    {id: "35",image:"./023.png" ,name: "Bộ Thun Lửng Bé Gái",price: "599.000" ,description: "Bộ thun lửng bé gái đơn giản nhưng trẻ trung, thích hợp cho bé mặc ở nhà hoặc khi đi dạo phố cùng gia đình."},
    {id: "36",image:"./025.png" ,name: "Bộ Shorts Karty Bé Gái",price: "399.000", description: " Bộ shorts Karty bé gái với kiểu dáng thời trang và màu sắc bắt mắt. Phối cùng áo thun sẽ tạo nên set đồ dễ thương và năng động cho bé."},
    {id: "37",image:"./037.png",name: "Bộ Đồ Thể Thao Nam",price: "899.000",description:"Bộ đồ thể thao nam với thiết kế trẻ trung, phong cách thể thao hiện đại. Bao gồm áo thun và quần short phù hợp cho các hoạt động thể thao nhẹ nhàng và đi chơi."},
    {id: "38",image:"./038.png" ,name: "Áo PoLo Nam",price: "499.000",description: "Áo Polo nam với chất liệu thoáng mát, phối hợp màu sắc trẻ trung. Thích hợp cho các hoạt động ngoài trời và cuộc sống hàng ngày."},
    {id: "39",image:"./040.png" ,name: "Áo PoLo Nam Hoa Tiet",price: "399.000",description: " Áo Polo nam hoa tiết đơn giản nhưng đầy phong cách, dễ phối đồ. Lựa chọn tuyệt vời cho những ngày xuân hè."},
    {id: "40",image:"./041.png" ,name: "Áo Sơ Mi Nam Flannel",price: "299.000",description: " Áo sơ mi nam dài tay với chất liệu vải flannel ấm áp, phù hợp cho mùa thu đông."},
    {id: "41",image:"./042.png" ,name: "Áo T-Shirt Nữ Dáng Rộng ",price: "199.000",description: " Áo T-shirt nữ dáng rộng, phong cách thời trang đơn giản nhưng thanh lịch. Lựa chọn hàng ngày cho phái đẹp."},
    {id: "42",image:"./043.png" ,name: "Áo Len Nữ Ngắn Tay Dệt Kẻ",price: "399.000",description: "Áo len nữ ngắn tay, chất liệu len dệt kẻ tinh tế, thích hợp cho mùa thu đông."},
    {id: "43",image:"./044.png" ,name: "Áo PoLo Nữ Mắt Chim",price: "299.000",description: ": Áo Polo nữ với họa tiết mắt chim trẻ trung, năng động. Phối cùng quần jeans hoặc chân váy làm nổi bật phong cách."},
    {id: "44",image:"./045.png" ,name: "Đầm Tiệc Nữ Sang Trọng",price: "399.000",description: "Đầm tiệc nữ sang trọng với thiết kế đẹp mắt, chất liệu cao cấp. Lựa chọn hoàn hảo cho các dịp đặc biệt."},
    {id: "45",image:"./046.png",name: "Áo Thun Trẻ Em Cổ Tròn", price: "99.500",description: "Áo thun trẻ em cổ tròn đơn giản, thoải mái cho các hoạt động ngoài trời."},
    {id: "46",image:"./050.png",name: "Áo Khoác Gió Trẻ Em ", price: "299.000",description: " Áo khoác gió trẻ em với thiết kế bảo vệ cơ thể bé trong những ngày gió lạnh."},
    {id: "47",image:"./048.png", name: "Áo Thun Trẻ Em Dài Tay ", price: "199.000",description: "Áo thun trẻ em dài tay với chất liệu cotton thoáng mát, phù hợp cho mọi mùa."},
    {id: "48",image:"./051.png",name: "Đầm Kid Hoạ Tiết Trái Tim", price: "299.000",description: "Đầm cho bé gái với hoạ tiết trái tim dễ thương, phong cách ngọt ngào."},
    {id: "49",image:"./047.png",name: "Áo Khoác Kid Nhỏ ", price: "99.500",description: "Áo khoác trẻ em nam nhỏ, dễ dàng mặc với mọi trang phục."},
    {id: "50",image:"./049.png",name: "Quần Dài Trẻ Em KaKi ", price: "299.000",description: "Quần dài trẻ em nam chất liệu kaki, bền chắc và thoải mái."},
    {id: "51",image:"./055.png", name: "Sơ Mi Trẻ Em Phối Mũ Nỉ", price: "199.000",description: "Sơ mi trẻ em nam phối mũ nỉ, giữ ấm và thời trang."},
    {id: "52",image:"./056.png",name: "Áo PoLo Thể Thao Trẻ Em", price: "299.000",description: "Áo Polo trẻ em nam thể thao, phối hợp màu sắc nổi bật, thích hợp cho các hoạt động ngoài trời."},
]